version: '3.8'

services:
  cr7-bot:
    build: .
    container_name: cr7-token-bot
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cr7-network

networks:
  cr7-network:
    driver: bridge

volumes:
  logs:
    driver: local
